### ISSUE TITLE
TimeoutError: 

### ISSUE THREAD

**Issue by andrewovchinnikov** [EmanuelCampos/opensea-script#2]
Hi, how can this be fixed?

TimeoutError: waiting for selector `.network-dropdown-content--link` failed: timeout 30000ms exceeded

**Comment by andrewovchinnikov** [comment]
TimeoutError: waiting for selector `.network-dropdown-content--link` failed: timeout 30000ms exceeded
    at null.WaitTask (C:\Users\andrew\Desktop\opensea-script-master\node_modules\puppeteer\src\common\DOMWorld.ts:813:28)
    at DOMWorld.waitForSelectorInPage (C:\Users\andrew\Desktop\opensea-script-master\node_modules\puppeteer\src\common\DOMWorld.ts:656:22)
    at Object.internalHandler.waitFor (C:\Users\andrew\Desktop\opensea-script-master\node_modules\puppeteer\src\common\QueryHandler.ts:78:19)
    at DOMWorld.waitForSelector (C:\Users\andrew\Desktop\opensea-script-master\node_modules\puppeteer\src\common\DOMWorld.ts:511:25)
    at Frame.waitForSelector (C:\Users\andrew\Desktop\opensea-script-master\node_modules\puppeteer\src\common\FrameManager.ts:1274:47)
    at Page.waitForSelector (C:\Users\andrew\Desktop\opensea-script-master\node_modules\puppeteer\src\common\Page.ts:3210:29)
    at C:\Users\andrew\Desktop\opensea-script-master\node_modules\@chainsafe\dappeteer\dist\index.js:136:51
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\andrew\Desktop\opensea-script-master\node_modules\@chainsafe\dappeteer\dist\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
